### ISSUE TITLE
HB issue

### ISSUE THREAD

**Issue by steveb85** [valkjsaaa/homebridge-switchmate3#4]
Hey, thanks for this. 

I’ve got my switchmate3 connected via node-switchmate3 and can toggle it and control it via SSH, i used @abandonware/Bluetooth-hci-socket and updated it to look for that, so that I could keep node min of 10. 

However, everytime i add to my config.json my homebridge is in constant shutdown. 

I’m wondering if it has to do with the fact, that even when using Node-switchmate3 i have to use SUDO in all commands, without it, it locks the system in finding the switch

Thoughts?
Config.json updates i made were from homebridge-Switchmate i tried with and without using 3 at the end of the platform name. 
Steve

**Comment by valkjsaaa** [comment]
You may have to use sudo since your Bluetooth hardware may require root permission.

**Comment by steveb85** [comment]
Thanks, I managed to work around that issue, and directed all the right hci.js to the abandonware hci version, so now i can command the light from command line, and i got the plugin to load in my homebridge without any issues, however, it says that no Switchmates are configured in the config.json the json is correct, and i found i needed to call the platform Switchmate3 but i can’t for the life of me figure out why it’s not loading the light. Is the same config.json here correct and current?

**Comment by steveb85** [comment]
Here is the top part of my config.json all the other platforms etc are working perfectly, and it’s throwing no errors, just not seeing the Switchmate


"bridge": {
"name": "Homebridge",
"username": "CD:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"description": "Homebridge",
"accessories": [ {
"accessory": "DelaySwitch",
"name": "KitchenFade",
"disableSensor": false,
"delay": 10000
},
{
"accessory": "DelaySwitch",
"name": "KitchenBright",
"disableSensor": false,
"delay": 10000
}
],
"platforms": [
{
"platform": "Switchmate3",
"switchmates": [
{
"displayName": "Bathroom",
"id": "da9f4252a7ba",
"model": "TSM003W",
"lowBatteryPercent": 25
}
]
}, {
"platform": "BroadlinkRM",
"name": "Broadlink RM",
"hideScanFrequencyButton": true,
"hideLearnButton": true,
"hideWelcomeMessage": true,
"accessories":

**Comment by steveb85** [comment]
Found the problem the platform needs to be switchmate3 and it needs to be switchmate3s not switchmates

**Comment by thehauntedmattress** [comment]
@steveb85 which file did you modify so that it looks for the abandonware bluetooth?

**Comment by steveb85** [comment]
@thehauntedmattress  

do something like $ find /usr -name hci.js that should give you a list of the files hci.js 

then you’ll have to sudo nano each file, and make sure it redirects to the @abandonware bluetooth one. It’s only once in each hci.js file, and it’s at the top, line 5, change to 

var BluetoothHciSocket = require('@abandonware/bluetooth-hci-socket');


You have to check through most of them, because it’s a bit nested in how it works, hard to explain with my knowledge, but it’s not too hard when you read through the files. From memory it was three files i had to change. LMK if that helps.

**Comment by thehauntedmattress** [comment]
@steveb85

Thank you so much.  Got it to work.

**Comment by thehauntedmattress** [comment]
@steveb85 

Also, can you post your config for switchmate3?

**Comment by steveb85** [comment]
platforms": [
{
"platform": "Switchmate3",
"switchmate3s": [
{
"displayName": "Bathroom",
"id": "da9f4252a7ba",
"model": "RSM003W",
"lowBatteryPercent": 25
}
]
},

**Comment by steveb85** [comment]
@thehauntedmattress  see above, sorry about the formatting. Figuring out the “switchmate3s” was the hard part that took ages only found it through logs

**Comment by thehauntedmattress** [comment]
So I am also using ssh commands to toggle mine, and every time I put a config to actually use homebridge-swtichmate3 it crashes homebridge on boot.  I definitely tried "switchmate3s".  But I'll try again.

**Comment by thehauntedmattress** [comment]
Okay so I did that and homebridge is running.  But it is not toggling the switch.

**Comment by steveb85** [comment]
Can you toggle the switch from command line?

Check through the homebridge logs

**Comment by thehauntedmattress** [comment]
I can toggle it through the CL, yes.  But if I can do it through switchmate3, I'd rather do it that way.

**Comment by steveb85** [comment]
If you can do it through CL, then it means the problem is in homebridge. Check the logs. @thehauntedmattress I believe i had some problems because with CL i could only get it to work when i used SUDO, and this was a problem i had to give every user access to Bluetooth hci, i can’t quite remember how i did that but it was a quick google.

**Comment by steveb85** [comment]
@thehauntedmattress how’d you go out of interest?

**Comment by thehauntedmattress** [comment]
@steveb85 I got this plugin to finally not crash HomeBridge, but it was not toggling the switch when I pressed the button.  I am now instead using [HomeBridge SSH](https://github.com/alguevara7/homebridge-ssh#readme).

These are the commands I am using to toggle the switch:

`cd /usr/lib/node_modules/homebridge-switchmate3/node_modules/node-switchmate3/bin/ && sudo node toggle.switchmate3 xxxxxxxxxx on`

`cd /usr/lib/node_modules/homebridge-switchmate3/node_modules/node-switchmate3/bin/ && sudo node toggle.switchmate3 xxxxxxxxxx off`

**Comment by steveb85** [comment]
@thehauntedmattress can you get it to toggle without the SUDO? I believe that’s where it’s going wrong, i had that trouble, but when i fixed it, everything came together correctly

**Comment by steveb85** [comment]
Either way glad it’s working now!

**Comment by thehauntedmattress** [comment]
When you say without SUDO do you mean through Homebridge SSH or using this switchmate3 plugin?

**Comment by steveb85** [comment]
I mean simply on command line

**Comment by thehauntedmattress** [comment]
But it works with SUDO.

**Comment by steveb85** [comment]
Yeah but i think if it needs SUDO, then that’s why it won’t work with the switchmate3 plugin that’s all. Sounds like its working for you so all good.

**Comment by thehauntedmattress** [comment]
I'm confused.  Can you explain more?  Because when I use Switchmate3 is it using SUDO or no?

**Comment by steveb85** [comment]
@thehauntedmattress HOmebridge and Switchmate3 don’t use SUDO. But there is a setting you can do in the system to give non sudo access to HCI Bluetooth protocol which is needed so that homebridge ‘ Switchmate3 can control the switch

**Comment by steveb85** [comment]
@thehauntedmattress HOmebridge and Switchmate3 don’t use SUDO. But there is a setting you can do in the system to give non sudo access to HCI Bluetooth protocol which is needed so that homebridge ‘ Switchmate3 can control the switch
